# Generated by Django 5.2.6 on 2025-09-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=7),
            preserve_default=False,
        ),
    ]
