# Generated by Django 5.2.6 on 2025-10-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_message_file_attachment_message_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
