# Generated by Django 5.2.6 on 2025-10-07 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_studysession_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
