# Generated by Django 5.2.6 on 2025-10-17 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_userprofile_suspended_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereport',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='base.message'),
        ),
    ]
